version: '3.7'

services:
  jenkins2:
    container_name: jenkins2
    image: desckjet/jenkins2docker
    environment:  
        JAVA_OPTS: "-Djava.awt.headless=true"  
        JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" 
    build:
      context: ./
    ports:
      - "8181:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net2
networks:
  net2:
