version: '3.7'

services:
  jenkins2:
    container_name: jenkins2
    image: desckjet/jenkins2docker
    build:
      context: ../
    ports:
      - "8181:8080"
    volumes:
      - ../../../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net2
networks:
  net2:
